### ISSUE TITLE
Failed to load a language-csharp package grammar

### ISSUE THREAD

**Issue by jiwantmg** [atom/language-csharp#133]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.1
**Thrown From**: [language-csharp](https://github.com/atom/language-csharp) package 1.1.0

### Stack Trace

Failed to load a language-csharp package grammar

```
At atom.grammars.startIdForScope is not a function in /usr/share/atom/resources/app.asar/node_modules/language-csharp/grammars/csharp.json

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191492)
    at GrammarRegistry.addGrammar (/usr/share/atom/resources/app/static/<embedded>:14:122537)
    at Grammar.activate (/usr/share/atom/resources/app/static/<embedded>:14:129719)
    at /usr/share/atom/resources/app/static/<embedded>:11:3575270
    at /usr/share/atom/resources/app/static/<embedded>:11:360749
    at u (/usr/share/atom/resources/app/static/<embedded>:11:581594)
    at /usr/share/atom/resources/app/static/<embedded>:11:582847
    at electron/js2c/asar.js:571:9
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5)
  at /app.asar/node_modules/language-csharp/grammars/csharp.json:1:1
```

### Commands

```
     -0:53.7.0 application:reopen-project (atom-pane.pane.active)
```

### Non-Core Packages

```
omnisharp-atom 0.31.2 
```

**Comment by jayjamesdr** [comment]
ArchLinux
Atom    : 1.55.0
Electron: 6.1.12

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/home/jay/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/usr/lib/atom/node_modules/first-mate/lib/grammar-registry.js:80:20)
    at Grammar.module.exports.Grammar.activate (/usr/lib/atom/node_modules/first-mate/lib/grammar.js:252:48)
    at /usr/lib/atom/src/package.js:717:47
    at /usr/lib/atom/src/grammar-registry.js:583:9
    at /usr/lib/atom/node_modules/season/lib/cson.js:219:59
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  at /home/jay/.atom/packages/language-csharp/grammars/csharp.cson:1:1

**Comment by andiethelion** [comment]
Atom: 1.53.0 x64
Electron: 6.1.12
OS: Ubuntu 20.04.1

TypeError: atom.grammars.startIdForScope is not a function
at grammarCb (/home/jay/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/usr/lib/atom/node_modules/first-mate/lib/grammar-registry.js:80:20)
at Grammar.module.exports.Grammar.activate (/usr/lib/atom/node_modules/first-mate/lib/grammar.js:252:48)
at /usr/lib/atom/src/package.js:717:47
at /usr/lib/atom/src/grammar-registry.js:583:9
at /usr/lib/atom/node_modules/season/lib/cson.js:219:59
at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
at /home/jay/.atom/packages/language-csharp/grammars/csharp.cson:1:1
